In [1]:
import pandas as pd
import numpy as np

In [2]:
i_cols=['movie id','movie title','release date','video release date','IMDb URL','unknown','Action','Adventure','Animation',
       'children\s','Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi',
        'Thriller','War','Western']
items=pd.read_csv('ml-100k/u.item', sep='|', names=i_cols, encoding='latin-1')

In [3]:
items.head(3)

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,children\s,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [4]:
movie_content=items[['movie id','movie title','Action','Adventure','Animation',
       'children\s','Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi',
        'Thriller','War','Western']]

In [5]:
movie_content

,movie id,movie title,Action,Adventure,Animation,children\s,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [7]:
r_cols=['user_id','movie_id','rating','unix_timestamp']
ratings=pd.read_csv('ml-100k/u.data',sep='\t',names=r_cols,encoding='latin-1')

In [8]:
ratings

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [10]:
ratings[ratings['user_id']==196][['movie_id','rating']]

       movie_id  rating
0           242       3
940         393       4
1133        381       4
1812        251       3
1896        655       5
2374         67       5
6910        306       4
7517        238       4
7842        663       5
10017       111       4
10254       580       2
10981        25       4
13733       286       5
14606        94       3
16834       692       5
17102         8       5
17830       428       4
18853      1118       4
21605        70       3
22271        66       3
22773       257       2
23189       108       4
24030       202       3
25726       340       3
32721       287       3
33536       116       3
35197       382       4
36281       285       5
41539      1241       3
42384      1007       4
50147       411       4
52726       153       5
56628        13       2
59165       762       3
59607       173       2
60199      1022       4
60706       845       4
78787       269       3
87863       110       1

In [11]:
datama=ratings.pivot_table(index='user_id',columns='movie_id',values='rating')

In [12]:
data_matrix=datama.replace(np.nan,0)

In [13]:
data_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
user_vector=data_matrix.T

In [15]:
user_vector

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
movie_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,4.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,4.0,...,2.0,3.0,4.0,0.0,4.0,0.0,0.0,5.0,0.0,0.0
2,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,4.0,...,5.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
5,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1679,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1682,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
movie_vec=items[['Action','Adventure','Animation',
       'children\s','Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi',
        'Thriller','War','Western']]

In [17]:
movie_vec.index=range(1,1683)

In [18]:
movie_vector=movie_vec.T

In [19]:
movie_vector

,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
Action,0,1,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Adventure,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Animation,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
children\s,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Comedy,1,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
Crime,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documentary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Drama,0,0,0,1,1,1,1,1,1,1,...,0,1,1,1,1,1,0,1,0,1
Fantasy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Film-Noir,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Horror,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Musical,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mystery,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
Sci-Fi,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Thriller,0,1,1,0,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
War,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
Western,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
u1=ratings[ratings['user_id']==1][['movie_id','rating']]

In [22]:
u1

       movie_id  rating
202          61       4
305         189       3
333          33       4
334         160       4
478          20       4
...         ...     ...
92049        28       4
92487       172       5
94019       122       3
96699       152       5
99073        94       2

[272 rows x 2 columns]

In [23]:
u1_list=[]
for i in u1['movie_id']:
    f=movie_vector[i].values
    u1_list.append(f)

In [24]:
uu1=pd.DataFrame(u1_list,columns=range(1,19))

In [25]:
uu1

     1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18
0     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
1     0   0   1   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
2     1   0   0   0   0   0   0   0   0   0   0   0   0   1   0   1   0   0
3     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
4     0   0   0   0   0   0   0   1   0   0   0   0   0   1   0   0   0   0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
267   1   0   0   0   0   0   0   1   0   0   0   0   0   0   0   1   0   0
268   1   1   0   0   0   0   0   1   0   0   0   0   0   1   1   0   1   0
269   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
270   0   0   0   0   1   0   0   0   0   0   0   0   0   0   1   0   0   0
271   0   0   0   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0

[272 rows x 18 columns]

In [27]:
vec=[]
for j in range(1,19):
     
    g=sum(uu1[j])
    vec.append(g/272)

In [28]:
vec

[0.2757352941176471,
 0.15441176470588236,
 0.04411764705882353,
 0.09191176470588236,
 0.33455882352941174,
 0.09191176470588236,
 0.01838235294117647,
 0.39338235294117646,
 0.007352941176470588,
 0.003676470588235294,
 0.04779411764705882,
 0.04779411764705882,
 0.01838235294117647,
 0.16176470588235295,
 0.15808823529411764,
 0.19117647058823528,
 0.09191176470588236,
 0.022058823529411766]

In [30]:
vector=[]
for user in range(1,944):
    u1=ratings[ratings['user_id']==user][['movie_id','rating']]
    u1_list=[]
    for i in u1 ['movie_id']:
        f=movie_vector[i].values
        u1_list.append(f)
    uu1=pd.DataFrame(u1_list,columns=range(1,19))
    vec=[]
    for j in range(1,19):
        g=sum(uu1[j])
        vec.append(g/len(u1))
    vector.append(vec)

In [34]:
def user_vector(ratings,movie_vector):
    vector=[]
    for user in range(1,944):
        u1=ratings[ratings['user_id']==user][['movie_id','rating']]
        u1_list=[]
        for i in u1['movie_id']:
            f=movie_vector[i].values
            u1_list.append(f)
            for j in range(1,19):
                g=sum(uu1[j])
                vec.append(g/len(u1))
                vector.append(vec)
        return vector

In [42]:
vector=user_vector(ratings,movie_vector)

In [43]:
users_vector=pd.DataFrame(vector)

In [45]:
users_vector

,0,1,2,3,4,5,6,7,8,9,...,9800,9801,9802,9803,9804,9805,9806,9807,9808,9809
0,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.0,0.339286,0.011905,0.0,...,0.007353,0.0,0.051471,0.014706,0.011029,0.121324,0.080882,0.128676,0.055147,0.033088
1,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.0,0.339286,0.011905,0.0,...,0.007353,0.0,0.051471,0.014706,0.011029,0.121324,0.080882,0.128676,0.055147,0.033088
2,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.0,0.339286,0.011905,0.0,...,0.007353,0.0,0.051471,0.014706,0.011029,0.121324,0.080882,0.128676,0.055147,0.033088
3,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.0,0.339286,0.011905,0.0,...,0.007353,0.0,0.051471,0.014706,0.011029,0.121324,0.080882,0.128676,0.055147,0.033088
4,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.0,0.339286,0.011905,0.0,...,0.007353,0.0,0.051471,0.014706,0.011029,0.121324,0.080882,0.128676,0.055147,0.033088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4891,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.0,0.339286,0.011905,0.0,...,0.007353,0.0,0.051471,0.014706,0.011029,0.121324,0.080882,0.128676,0.055147,0.033088
4892,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.0,0.339286,0.011905,0.0,...,0.007353,0.0,0.051471,0.014706,0.011029,0.121324,0.080882,0.128676,0.055147,0.033088
4893,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.0,0.339286,0.011905,0.0,...,0.007353,0.0,0.051471,0.014706,0.011029,0.121324,0.080882,0.128676,0.055147,0.033088
4894,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.0,0.339286,0.011905,0.0,...,0.007353,0.0,0.051471,0.014706,0.011029,0.121324,0.080882,0.128676,0.055147,0.033088
4895,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.0,0.339286,0.011905,0.0,...,0.007353,0.0,0.051471,0.014706,0.011029,0.121324,0.080882,0.128676,0.055147,0.033088

(100000, 4)